language: java  
jdk:  
  - oraclejdk8  
before_install:  
  - "echo skipped"  
install:  
  - "echo skipped"  
script:  
  - "echo skipped"
after_success:
  - bash <(curl -s https://codecov.io/bash)
